import 'dart:math';

String randomQuote=quotes[Random().nextInt(100)];
List<String> quotes = [
  "Believe in yourself and all that you are.",
  "Dream big, work hard, and stay focused.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The key to success is to focus on goals, not obstacles.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Your life does not get better by chance, it gets better by change.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Great things never come from comfort zones.",
  "Dream it. Believe it. Build it.",
  "Don’t wait for opportunity. Create it.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The secret to getting ahead is getting started.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen, you create them.",
  "Don't wait. The time will never be just right.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It always seems impossible until it's done.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Hard work beats talent when talent doesn't work hard.",
  "Don’t limit your challenges, challenge your limits.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Everything you can imagine is real.",
  "Do one thing every day that scares you.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The way to get started is to quit talking and begin doing.",
  "Your passion is waiting for your courage to catch up.",
  "The difference between who you are and who you want to be is what you do.",
  "Success is not in what you have, but who you are.",
  "If you can dream it, you can do it.",
  "Go the extra mile. It's never crowded.",
  "Act as if it is impossible to fail.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "It always seems impossible until it’s done.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Happiness is not something ready made. It comes from your own actions.",
  "If you want to lift yourself up, lift up someone else.",
  "Do what you can with all you have, wherever you are.",
  "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don’t be afraid to give up the good to go for the great.",
  "If you want to achieve greatness stop asking for permission.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "Success is the ability to go from one failure to another with no loss of enthusiasm.",
  "Life is what happens when you’re busy making other plans.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Don’t watch the clock; do what it does. Keep going.",
  "You are never too old to set another goal or to dream a new dream.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "Don’t wait for the perfect moment. Take the moment and make it perfect.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Believe you can and you're halfway there.",
  "Do what you can, with what you have, where you are.",
  "Success isn’t just about what you accomplish in your life, it’s about what you inspire others to do.",
  "Success is not in what you have, but who you are.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The best way to predict the future is to create it.",
  "We become what we think about.",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "Limit your ‘always’ and your ‘nevers.’",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "You don’t have to be perfect to be amazing.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is not for the chosen few, but for the few who choose it.",
  "Act as if what you do makes a difference. It does.",
  "Don’t wait for the right opportunity, create it.",
  "What we think, we become.",
  "The only way to do great work is to love what you do.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your limitation—it’s only your imagination.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Great things never come from comfort zones.",
  "Dream it. Believe it. Achieve it.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It’s not the years in your life that count, it’s the life in your years.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Don’t be afraid to give up the good to go for the great.",
  "Success is walking from failure to failure with no loss of enthusiasm."
];
